apiVersion: v1
kind: Pod
metadata:
 name: pod2
 labels:
  app: time
  env: prod
 annotations:
  owner: girish
  role: dev
spec:
 containers:
 - name: nginx1
   image: nginx
   ports:
   - containerPort: 80

