apiVersion: v1
kind: Pod
metadata:
 labels:
  app: myapp-1
 name: my-podns
 namespace: my-ns
spec:
 containers:
 - name: mycon
   image: busybox
   command: ['sh','-c','echo helloworld girish && sleep 3600']

