apiVersion: v1
kind: Pod
metadata:
 labels:
  app: myapp-1
 name: my-podns
 namespace: my-ns
spec:
 containers:
 - name: mycon
   image: busybox
   command: ['sh','-c','echo helloworld $(myvar2) $(myvar)']
   env:
   - name: myvar
     valueFrom:
      configMapKeyRef:
       name: my-config-map
       key: name
   - name: myvar2
     valueFrom:
      configMapKeyRef:
       name: my-config-map
       key: my-key
 

