apiVersion: v1
kind: Pod
metadata:
 namespace: my-ns
 name: my-rl
spec:
 containers:
 - name: my-con
   image: busybox
   command: ['sh','-c','echo helloworld && sleep 3600']
   resources:
    requests:
     cpu: "250m"
     memory: "64Mi"
    limits:
     cpu: "500m"
     memory: '128Mi'
